# Generated by Django 4.2.16 on 2024-11-16 23:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsHub', '0002_supportquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
