# Generated by Django 5.1.4 on 2025-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelsHub', '0003_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='contact',
            field=models.CharField(max_length=150),
        ),
    ]
